#-*- coding: utf-8 -*-

{
	"name": "peminjaman_asset",
	"version": "1.0", 
	"depends": [
		'base',
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the peminjaman_asset module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/transaction.xml",
		"view/borrower_asset.xml",
		"view/borrowed_asset.xml",
		"view/assets.xml",
		"view/uom.xml",
		"report/transaction.xml",
		"report/borrower_asset.xml",
		"report/borrowed_asset.xml",
		"report/assets.xml",
		"report/uom.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}